---
all:
  children:
    DC:
      children:
        ipn:
          hosts:
            ipn.nt01:
              ansible_host: '10.166.30.51'
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-a-01.cfg
            ipn.nt02:
              ansible_host: '10.166.30.52' 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-a-02.cfg
            ipn.qf01:
              ansible_host: '10.166.30.53' 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-b-01.cfg
            ipn.qf02:
              ansible_host: '10.166.30.54' 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-b-02.cfg
...
