---
all:
  children:
    DC:
      children:
        ipn:
          hosts:
            ipn.nt01:
              ansible_host: clab-nxos_ipn-ipn-a-01 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-a-01.cfg
            ipn.nt02:
              ansible_host: clab-nxos_ipn-ipn-a-02 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-a-02.cfg
            ipn.qf01:
              ansible_host: clab-nxos_ipn-ipn-b-01 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-b-01.cfg
            ipn.qf02:
              ansible_host: clab-nxos_ipn-ipn-b-02 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
              config_file: ipn-b-02.cfg
...
