---
all:
  children:
    DC:
      children:
        ipn:
          hosts:
            ipn.nt01:
              ansible_host: clab-nxos_ipn-ipn-a-01 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
            ipn.nt02:
              ansible_host: clab-nxos_ipn-ipn-a-02 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
            ipn.qf01:
              ansible_host: clab-nxos_ipn-ipn-b-01 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
            ipn.qf02:
              ansible_host: clab-nxos_ipn-ipn-b-02 
              ansible_user: '{{ lookup("env", "IPN_USER")}}'
              ansible_password: '{{ lookup("env", "IPN_PASSWORD")}}'
              ansible_network_os: 'nxos'
...
