---
# ============================================================================
# Define Anchors
# ============================================================================

- name:
  hosts: ipn
  gather_facts: false

  tasks:
    block:
      - name: INITIAL SNAPSHOT
        cisco.nxos.nxos_command:
          commands:
            - 'checkpoint INIT description Initial_config'

      - name: CLEAN Config
        cisco.nxos.nxos_config:
          lines:
            - 'no feature telnet'
            - 'no feature nxapi'
            - 'no feature scp-server'
            - 'no feature netconf'
            - 'no feature grpc'
            - 'no system default switchport'
            - 'system default switchport shutdown'
      tags:
        - snapshot

    - name: TEST
      cisco.nxos.nxos_config:
        src: "{{ config_file }}"
      tags:
        - deploy
...
