---
# ============================================================================
# Define Anchors
# ============================================================================

- name:
  hosts: ipn
  gather_facts: false

  tasks:
    - name: INITIAL SETUP
      block:
        - name: Make Some cleanning
          cisco.nxos.nxos_config:
            lines:
              # - 'no feature telnet'
              # - 'no feature nxapi'
              # - 'no feature scp-server'
              # - 'no feature netconf'
              # - 'no feature grpc'
              - 'no system default switchport'
              - 'system default switchport shutdown'

        - name: Pause for 60s
          ansible.builtin.pause:
            seconds: 60

        - name: Create Initial SNAPSHOT
          cisco.nxos.nxos_command:
            commands:
              - 'checkpoint INIT description Initial_config'

        - name: Pause for 60s
          ansible.builtin.pause:
            seconds: 60
      tags:
        - snapshot

    - name: TEST
      cisco.nxos.nxos_config:
        src: "{{ config_file }}"
      tags:
        - deploy
...
