---
# ============================================================================
# Define Anchors
# ============================================================================

- name:
  hosts: ipn
  gather_facts: false

  tasks:
    - name: INITIAL SNAPSHOT
      cisco.nxos.nxos_command:
        commands:
          - 'checkpoint INIT description Initial_config'
      tags:
        - snapshot

    - name: RELOAD IN
      cisco.nxos.nxos_command:
        commands:
          - 'reload in 600'
      when: ansible_host == '10.166.30.51'
      tags:
        - reload_in

    - name: Deply config
      cisco.nxos.nxos_config:
        src: "{{ config_file }}"
      when: ansible_host == '10.166.30.51'
      notify:
        - Cancel Reload
      tags:
        - deploy

  handlers:
    - name: Cancel Reload
      cisco.nxos.nxos_command:
        commands:
          - 'reload in 600'
...
