---
# ============================================================================
# Define Anchors
# ============================================================================

- name:
  hosts: ipn
  gather_facts: false

  tasks:
    - name: INITIAL SNAPSHOT
      cisco.nxos.nxos_command:
        commands:
          - 'no feature telnet'
          - 'no feature nxapi'
          - 'no feature scp-server'
          - 'no feature netconf'
          - 'no feature grpc'
          - 'checkpoint INIT description Initial_config'
      tags:
        - snapshot

    - name: TEST
      cisco.nxos.nxos_config:
        src: "{{ config_file }}"
      tags:
        - deploy
...
