---
# ============================================================================
# Define Anchors
# ============================================================================

- name:
  hosts: ipn
  gather_facts: false

  tasks:
    - name: TEST
      cisco.nxos.nxos_config:
        src: "{{ config_file }}" 
...
